languageCode = "en-us"
title = "Alex Dawson - Portfolio"

theme = "portfolio-theme"

[params]
    AuthorName = "Alex Dawson"
    GitHubUser = "dawsonalex"
    TwitterUser = "_dawson_alex"
    LinkedInUser = "dawsonal"

    projectsURL = "" # URL to projects JSON