# Navigation links, the menu at the top of all pages has the name "header"

[[header]]
    name = "Posts"
    url = "/posts/"
    weight = 10

[[header]]
    name = "Projects"
    url = "/projects/"
    weight = 10

[[header]]
    name = "Tags"
    url = "/tags/"
    weight = 10