# Site author
author = "Alex Dawson"
subtitle = "Full Stack Developer"

description="A collection of posts and project pieces from software engineer Alex Dawson"

# list of links for external site accounts
contact_links = [
    {icon = "twitter", link = "https://twitter.com/_dawson_alex"},
    {icon = "github", link = "https://github.com/dawsonalex"},
    {icon = "linkedin", link = "https://linkedin.com/in/dawsonal"},
    {icon = "rss", link = "/index.xml"}
]

# URL to get project JSON on build
projectsURL = ""