[build]
    publish = "public"
    command = "hugo --gc --minify"
    #functions = "functions"

[build.environment]
    HUGO_VERSION = "0.71.1"

[context.branch-deploy]
    command = "sed -i 's/SUBDOMAIN_PLACEHOLDER/$DEPLOY_PRIME_URL./g' netlify.toml && hugo --gc --minify"

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "https://SUBDOMAIN_PLACEHOLDERdawsona.co.uk"
