[build]
    publish = "public"
    command = "hugo --gc --minify"
    #functions = "functions"

[build.environment]
    HUGO_VERSION = "0.71.1"

[context.branch-deploy]
    command = 'hugo --gc --minify -b $URL' 