[build]
    publish = "public"
    command = "hugo --gc --minify"
    #functions = "functions"

[[redirects]]
	from = "/*"
	to = "404.html"
	status = 404

[build.environment]
    HUGO_VERSION = "0.71.1"

[context.branch-deploy]
    command = 'hugo --gc --minify -b https://$BRANCH.dawsona.co.uk' 

[[headers]]
    for="/fonts/*"
    [headers.values]
    # cache for one month
    Cache-Control="public, max-age=2628002"

    for="/site.webmanifest"
    [headers.values]
    Content-Type="application/manifest+json"