[build]
    publish = "public"
    command = "hugo --gc --minify"
    #functions = "functions"

[build.environment]
    HUGO_VERSION = "0.71.1"

[[headers]]
    for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*.dawsona.co.uk"