[build]
    publish = "public"
    command = "make production"
    #functions = "functions"

[[redirects]]
	from = "/*"
	to = "404.html"
	status = 404

[build.environment]
    HUGO_VERSION = "0.82.0"

[context.branch-deploy]
    command = 'make deploy_preview BRANCH=$BRANCH'
