# Wrangler config taken from https://gohugo.io/host-and-deploy/host-on-cloudflare/
name = "portfolio"
compatibility_date = "2026-06-10"
compatibility_flags = ["nodejs_compat"]

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"

[observability]
enabled = true